// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/5bdb771c877c0455839c34e4190656764915e3a1/i18next-node-fs-backend/i18next-node-fs-backend.d.ts
declare namespace I18next {
    interface I18nextOptions extends i18nextNodeFsBackEnd.I18nextOptions { }
}

declare namespace i18nextNodeFsBackEnd {
    /**
     * @summary Options for "i18next-node-fs-backend".
     * @interface
     */
    interface i18nextNodeFsBackEndOptions {
        // path where resources get loaded from
        /**
         * @summary Path where resources get loaded from.
         * @type {string}
         */
        loadPath: string;

        /**
         * @summary Path to post missing resources
         * @type {string}
         */
        addPath: string;

        /**
         * @summary jsonIndent to use when storing json files
         * @type {number}
         */
        //
        jsonIndent: number;
    }

    /**
     * @summary Options for "i18next".
     * @interface
     */
    interface I18nextOptions {
        backend?: i18nextNodeFsBackEndOptions;
    }
}

declare module "i18next-node-fs-backend" {
    import * as i18next from "i18next";

    class BackEnd {
        constructor(services?: any, options?: Object);
        init(options?: Object): void;
    }

    var out: typeof BackEnd;
    export = out;
}